version: '2'
services:
  consul-server-1:
    build: .
    container_name: consul-server-1
    networks:
      wee-net:
        ipv4_address: 172.16.238.2
    volumes:
      - ../server1_config:/consul/config
  consul-server-2:
    build: .
    container_name: consul-server-2
    networks:
      wee-net:
        ipv4_address: 172.16.238.3
    volumes:
      - ../server2_config:/consul/config

networks:
  wee-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
